const express = require('express');
const router = express.Router();
const User = require('../models/User');
const Place = require('../models/Place');

const SAMPLE_LISTINGS = [
  {
    title: 'Cozy Mountain Cabin with Stunning Views',
    address: 'Aspen, Colorado, United States',
    photos: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
      'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800',
    ],
    description: 'Escape to this charming mountain cabin nestled in the heart of the Rockies. Enjoy breathtaking views, a cozy fireplace, and easy access to world-class skiing and hiking trails.',
    perks: ['wifi', 'parking', 'tv', 'pets'],
    extraInfo: 'Check-in after 3 PM. No smoking indoors.',
    maxGuests: 6,
    price: 185,
  },
  {
    title: 'Modern Loft in Downtown Arts District',
    address: 'Los Angeles, California, United States',
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    description: 'Stylish loft apartment in the vibrant Arts District. Walking distance to galleries, restaurants, and nightlife. Features exposed brick walls and floor-to-ceiling windows.',
    perks: ['wifi', 'tv', 'entrance'],
    extraInfo: 'Building has elevator access. Rooftop terrace available.',
    maxGuests: 4,
    price: 150,
  },
  {
    title: 'Beachfront Villa with Private Pool',
    address: 'Tulum, Quintana Roo, Mexico',
    photos: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800',
    ],
    description: 'Wake up to the sound of waves in this stunning beachfront villa. Features a private infinity pool, outdoor shower, and direct beach access.',
    perks: ['wifi', 'parking', 'tv', 'pets'],
    extraInfo: 'Private chef available upon request. Airport transfers included.',
    maxGuests: 8,
    price: 320,
  },
  {
    title: 'Charming Cottage in the Countryside',
    address: 'Cotswolds, England, United Kingdom',
    photos: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    description: 'A quintessential English countryside cottage with a thatched roof, beautiful gardens, and a warm fireplace. Perfect for a peaceful retreat.',
    perks: ['wifi', 'parking', 'pets'],
    extraInfo: 'Fresh eggs from our chickens available each morning!',
    maxGuests: 4,
    price: 130,
  },
  {
    title: 'Luxury Penthouse with City Skyline Views',
    address: 'New York City, New York, United States',
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    description: 'Experience Manhattan from this stunning penthouse with panoramic skyline views. Features floor-to-ceiling windows, designer furniture, and a private terrace.',
    perks: ['wifi', 'tv', 'entrance'],
    extraInfo: 'Doorman building with 24/7 concierge. Gym and rooftop access included.',
    maxGuests: 2,
    price: 450,
  },
  {
    title: 'Traditional Riad with Rooftop Terrace',
    address: 'Marrakech, Morocco',
    photos: [
      'https://images.unsplash.com/photo-1539437829697-1b4ed5aebd19?w=800',
      'https://images.unsplash.com/photo-1528255671579-01b9e182ed1d?w=800',
    ],
    description: 'Stay in a beautifully restored traditional riad in the heart of the Medina. Features a stunning courtyard with a plunge pool and a rooftop terrace with Atlas Mountain views.',
    perks: ['wifi', 'tv'],
    extraInfo: 'Breakfast included. Walking tours of the Medina can be arranged.',
    maxGuests: 6,
    price: 95,
  },
  {
    title: 'Scandinavian A-Frame in the Forest',
    address: 'Bergen, Norway',
    photos: [
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800',
      'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800',
    ],
    description: 'A stunning A-frame cabin surrounded by Norwegian forest. Floor-to-ceiling windows bring nature inside. Perfect for hiking in summer and aurora viewing in winter.',
    perks: ['wifi', 'parking'],
    extraInfo: 'Firewood provided. Nearest grocery store is 10 minutes by car.',
    maxGuests: 4,
    price: 175,
  },
  {
    title: 'Sunny Apartment Near the Acropolis',
    address: 'Athens, Greece',
    photos: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
    ],
    description: 'Bright, airy apartment with a balcony overlooking the Acropolis. Located in the charming Plaka neighborhood, steps from historic sites, tavernas, and shops.',
    perks: ['wifi', 'tv', 'entrance'],
    extraInfo: 'AC included. Walking map of Athens provided.',
    maxGuests: 3,
    price: 110,
  },
  {
    title: 'Tropical Treehouse Retreat',
    address: 'Ubud, Bali, Indonesia',
    photos: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800',
    ],
    description: 'Sleep among the treetops in this bamboo treehouse surrounded by rice paddies. Features an open-air bathroom, private plunge pool, and stunning jungle views.',
    perks: ['wifi', 'parking', 'pets'],
    extraInfo: 'Complimentary yoga class every morning. Shuttle to Ubud center available.',
    maxGuests: 2,
    price: 140,
  },
  {
    title: 'Historic Brownstone in Back Bay',
    address: 'Boston, Massachusetts, United States',
    photos: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    description: 'Elegant brownstone apartment in one of Boston\'s most prestigious neighborhoods. Original hardwood floors, crown molding, and a private garden patio.',
    perks: ['wifi', 'tv', 'entrance'],
    extraInfo: 'Near the T Green Line. No parties please.',
    maxGuests: 4,
    price: 220,
  },
  {
    title: 'Lakefront Log Cabin',
    address: 'Lake Tahoe, California, United States',
    photos: [
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
    ],
    description: 'Rustic log cabin right on the shores of Lake Tahoe. Private dock, kayaks included, and a hot tub on the deck with lake views.',
    perks: ['wifi', 'parking', 'tv', 'pets'],
    extraInfo: 'Kayaks and paddleboards available. Firewood included in winter.',
    maxGuests: 8,
    price: 275,
  },
  {
    title: 'Minimalist Studio in Shibuya',
    address: 'Tokyo, Japan',
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    description: 'Sleek, modern studio in the heart of Shibuya. Walking distance to the famous crossing, Meiji Shrine, and Harajuku. Features a rain shower and smart home controls.',
    perks: ['wifi', 'tv', 'entrance'],
    extraInfo: 'Pocket WiFi device provided. 2-minute walk to Shibuya Station.',
    maxGuests: 2,
    price: 120,
  },
  {
    title: 'Cliffside Villa with Caldera Views',
    address: 'Santorini, Greece',
    photos: [
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800',
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
    ],
    description: 'Iconic whitewashed villa perched on the caldera cliffs of Oia. Private infinity pool, outdoor dining area, and unobstructed sunset views over the Aegean Sea.',
    perks: ['wifi', 'tv', 'parking'],
    extraInfo: 'Airport transfer included. Wine tasting tours arranged on request.',
    maxGuests: 4,
    price: 380,
  },
  {
    title: 'Converted Warehouse Loft',
    address: 'Melbourne, Victoria, Australia',
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    description: 'Industrial-chic warehouse conversion in Fitzroy. Soaring ceilings, polished concrete floors, and original brick walls. Steps from cafes, bars, and street art.',
    perks: ['wifi', 'tv', 'entrance', 'parking'],
    extraInfo: 'Bikes available for guest use. Rooftop BBQ area shared.',
    maxGuests: 3,
    price: 165,
  },
  {
    title: 'Desert Oasis with Hot Springs',
    address: 'Joshua Tree, California, United States',
    photos: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800',
    ],
    description: 'Off-grid desert retreat featuring a natural hot spring pool, outdoor shower, and unparalleled stargazing. The perfect digital detox escape.',
    perks: ['parking', 'pets'],
    extraInfo: 'Limited cell service by design. 4WD recommended. Firewood provided.',
    maxGuests: 4,
    price: 195,
  },
  {
    title: 'Canal House in Jordaan',
    address: 'Amsterdam, Netherlands',
    photos: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    description: 'Charming 17th-century canal house in Amsterdam\'s most sought-after neighborhood. Steep Dutch stairs lead to a cozy apartment with canal views and exposed beam ceilings.',
    perks: ['wifi', 'tv'],
    extraInfo: 'Steep traditional stairs — not suitable for mobility issues. Bike rental nearby.',
    maxGuests: 3,
    price: 190,
  },
  {
    title: 'Safari Lodge with Wildlife Views',
    address: 'Maasai Mara, Kenya',
    photos: [
      'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
    ],
    description: 'Luxury tented safari lodge overlooking the Mara River. Watch elephants and hippos from your private veranda. All-inclusive with guided game drives twice daily.',
    perks: ['wifi', 'parking'],
    extraInfo: 'All meals and game drives included. Malaria prophylaxis recommended.',
    maxGuests: 2,
    price: 550,
  },
  {
    title: 'Houseboat on the Backwaters',
    address: 'Alleppey, Kerala, India',
    photos: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
    ],
    description: 'Traditional kettuvallam houseboat cruising the tranquil Kerala backwaters. Private crew, freshly prepared local cuisine, and stunning sunset views over the lagoons.',
    perks: ['wifi', 'pets'],
    extraInfo: 'All meals included. Captain and cook on board. Stops at local villages.',
    maxGuests: 4,
    price: 85,
  },
  {
    title: 'Glass Igloo Under the Northern Lights',
    address: 'Rovaniemi, Lapland, Finland',
    photos: [
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800',
      'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800',
    ],
    description: 'Sleep under the northern lights in a heated glass igloo. The thermal glass ceiling gives you a front-row seat to the aurora borealis from the comfort of your bed.',
    perks: ['wifi', 'parking'],
    extraInfo: 'Aurora alarm provided. Snowmobile and reindeer safaris bookable on site.',
    maxGuests: 2,
    price: 310,
  },
  {
    title: 'Art Deco Apartment in South Beach',
    address: 'Miami Beach, Florida, United States',
    photos: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    description: 'Restored Art Deco gem one block from the beach on Ocean Drive. Pastel interiors, terrazzo floors, and a rooftop pool with views of the Atlantic.',
    perks: ['wifi', 'tv', 'entrance'],
    extraInfo: 'Beach chairs and umbrella provided. Valet parking available for $25/day.',
    maxGuests: 4,
    price: 200,
  },
  {
    title: 'Stone Farmhouse in Tuscany',
    address: 'Chianti, Tuscany, Italy',
    photos: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    description: 'Restored 18th-century stone farmhouse surrounded by vineyards and olive groves. Features a wood-fired pizza oven, swimming pool, and panoramic hilltop views.',
    perks: ['wifi', 'parking', 'tv', 'pets'],
    extraInfo: 'Wine tasting at the estate vineyard included. Cooking classes available.',
    maxGuests: 10,
    price: 290,
  },
  {
    title: 'Cozy Chalet in the Swiss Alps',
    address: 'Zermatt, Switzerland',
    photos: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
      'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800',
    ],
    description: 'Traditional Swiss chalet with direct views of the Matterhorn. Wood-burning fireplace, sauna, and ski-in/ski-out access to the Zermatt slopes.',
    perks: ['wifi', 'parking', 'tv'],
    extraInfo: 'Ski storage and boot warmers provided. Car-free village — train access only.',
    maxGuests: 6,
    price: 340,
  },
  {
    title: 'Floating Bungalow on the River',
    address: 'Kanchanaburi, Thailand',
    photos: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800',
    ],
    description: 'Thatched-roof bungalow floating on the River Kwai. Fall asleep to the gentle rocking of the water and wake up to misty mountain views and birdsong.',
    perks: ['wifi', 'parking'],
    extraInfo: 'Kayak and bamboo raft included. Restaurant on site.',
    maxGuests: 2,
    price: 60,
  },
  {
    title: 'Penthouse Suite in Downtown Dubai',
    address: 'Dubai Marina, Dubai, UAE',
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    description: 'Ultra-luxurious penthouse in Dubai Marina with floor-to-ceiling windows showcasing the Palm Jumeirah and Arabian Gulf. Private elevator, marble finishes, and smart home throughout.',
    perks: ['wifi', 'tv', 'parking', 'entrance'],
    extraInfo: 'Concierge service 24/7. Private beach access. Chauffeur available.',
    maxGuests: 6,
    price: 650,
  },
  {
    title: 'Vineyard Cottage in Napa Valley',
    address: 'Napa Valley, California, United States',
    photos: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    description: 'Charming guest cottage nestled among the vines of a working winery. Private patio, outdoor firepit, and complimentary wine tasting at the estate.',
    perks: ['wifi', 'parking', 'pets'],
    extraInfo: 'Bottle of estate wine on arrival. Hot air balloon rides bookable.',
    maxGuests: 2,
    price: 250,
  },
  {
    title: 'Georgian Townhouse in Edinburgh',
    address: 'Edinburgh, Scotland, United Kingdom',
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    description: 'Elegant Georgian townhouse in Edinburgh\'s New Town. High ceilings, period features, and views of Edinburgh Castle. Walking distance to the Royal Mile.',
    perks: ['wifi', 'tv', 'entrance'],
    extraInfo: 'Whisky welcome package included. Festival season books up fast.',
    maxGuests: 5,
    price: 195,
  },
  {
    title: 'Eco-Lodge in the Cloud Forest',
    address: 'Monteverde, Costa Rica',
    photos: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
      'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800',
    ],
    description: 'Sustainable eco-lodge perched on the edge of the Monteverde Cloud Forest. Solar-powered, with a private balcony for bird watching and zip-line tours nearby.',
    perks: ['wifi', 'parking'],
    extraInfo: 'Guided nature walks included. Rubber boots provided for forest trails.',
    maxGuests: 3,
    price: 110,
  },
  {
    title: 'Seaside Cottage on Cape Cod',
    address: 'Provincetown, Massachusetts, United States',
    photos: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800',
    ],
    description: 'Quintessential Cape Cod cottage steps from the beach. White picket fence, hydrangea garden, and a screened porch perfect for reading with ocean breezes.',
    perks: ['wifi', 'parking', 'pets'],
    extraInfo: 'Beach towels and chairs provided. Outdoor shower for sandy feet.',
    maxGuests: 5,
    price: 175,
  },
  {
    title: 'Luxury Yurt in Patagonia',
    address: 'Torres del Paine, Chile',
    photos: [
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800',
      'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800',
    ],
    description: 'Glamping yurt with views of the Torres del Paine peaks. Wood-burning stove, sheepskin rugs, and a private outdoor hot tub under the Patagonian sky.',
    perks: ['parking'],
    extraInfo: 'Guided treks available. All meals can be arranged. Wind can be intense.',
    maxGuests: 2,
    price: 230,
  },
  {
    title: 'Renovated Trullo in Puglia',
    address: 'Alberobello, Puglia, Italy',
    photos: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
    ],
    description: 'Stay in an iconic cone-roofed trullo, lovingly restored with modern comforts. Whitewashed stone walls, vaulted ceilings, and a private garden with fig trees.',
    perks: ['wifi', 'parking', 'tv'],
    extraInfo: 'Olive oil and local wine provided. Cooking class with a nonna bookable.',
    maxGuests: 4,
    price: 135,
  },
  {
    title: 'Oceanfront Condo in Waikiki',
    address: 'Honolulu, Hawaii, United States',
    photos: [
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800',
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
    ],
    description: 'Modern high-rise condo with a private lanai overlooking Waikiki Beach and Diamond Head. Full kitchen, resort pool, and steps from world-class surfing.',
    perks: ['wifi', 'tv', 'entrance', 'parking'],
    extraInfo: 'Beach gear and snorkeling equipment provided. Luau tickets available.',
    maxGuests: 4,
    price: 280,
  },
  {
    title: 'Mountain Refuge in the Dolomites',
    address: 'Cortina d\'Ampezzo, Italy',
    photos: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800',
    ],
    description: 'Alpine refuge with jaw-dropping Dolomite views. Warm wood interiors, a bubbling hot tub on the terrace, and direct access to Via Ferrata climbing routes.',
    perks: ['wifi', 'parking', 'tv'],
    extraInfo: 'Ski pass discounts available. Hearty Italian breakfast included.',
    maxGuests: 6,
    price: 210,
  },
  {
    title: 'Colonial Mansion in Old Havana',
    address: 'Havana, Cuba',
    photos: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    description: 'Grand colonial mansion with soaring ceilings, colorful tiles, and a lush interior courtyard. In the heart of Old Havana, surrounded by live music and history.',
    perks: ['wifi', 'parking'],
    extraInfo: 'Classic car tours arranged. Salsa lessons available on the rooftop.',
    maxGuests: 6,
    price: 75,
  },
  {
    title: 'Ski-In Condo at Whistler Village',
    address: 'Whistler, British Columbia, Canada',
    photos: [
      'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
    ],
    description: 'Slope-side condo with ski-in/ski-out access to Whistler Blackcomb. Stone fireplace, heated floors, and a shared outdoor hot tub with mountain views.',
    perks: ['wifi', 'tv', 'parking'],
    extraInfo: 'Ski storage and tuning room on site. Village shops and dining steps away.',
    maxGuests: 6,
    price: 300,
  },
  {
    title: 'Bohemian Flat in Le Marais',
    address: 'Paris, France',
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    description: 'Romantic Parisian flat in the trendy Le Marais district. Exposed beams, vintage furnishings, and a Juliet balcony overlooking a quiet cobblestone street.',
    perks: ['wifi', 'tv', 'entrance'],
    extraInfo: 'Bakery next door. Metro station 1 minute away. No elevator (4th floor).',
    maxGuests: 2,
    price: 170,
  },
  {
    title: 'Riverside Bamboo Villa',
    address: 'Luang Prabang, Laos',
    photos: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800',
    ],
    description: 'Open-air bamboo villa on the banks of the Mekong River. Teak and bamboo construction, mosquito-netted bed, and a private deck for watching the river life pass by.',
    perks: ['wifi', 'parking'],
    extraInfo: 'Alms giving ceremony viewable at dawn. Boat trips to Pak Ou Caves arranged.',
    maxGuests: 2,
    price: 55,
  },
  {
    title: 'Loft with Harbour Bridge Views',
    address: 'Sydney, New South Wales, Australia',
    photos: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    description: 'Contemporary loft in The Rocks with floor-to-ceiling windows framing the Harbour Bridge and Opera House. Designer kitchen, rain shower, and rooftop terrace.',
    perks: ['wifi', 'tv', 'entrance'],
    extraInfo: 'Ferry terminal 5-minute walk. New Year\'s Eve fireworks visible from terrace.',
    maxGuests: 3,
    price: 260,
  },
  {
    title: 'Adobe Casita in Santa Fe',
    address: 'Santa Fe, New Mexico, United States',
    photos: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
    ],
    description: 'Authentic adobe casita with a kiva fireplace, saltillo tile floors, and a private courtyard with a hot tub. Walking distance to the historic Plaza and Canyon Road galleries.',
    perks: ['wifi', 'parking', 'tv', 'pets'],
    extraInfo: 'Firewood for kiva provided. Margarita welcome kit on arrival.',
    maxGuests: 4,
    price: 160,
  },
  {
    title: 'Overwater Bungalow',
    address: 'Bora Bora, French Polynesia',
    photos: [
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800',
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
    ],
    description: 'Iconic overwater bungalow with a glass floor panel to watch tropical fish below. Private deck with ladder into the turquoise lagoon and views of Mount Otemanu.',
    perks: ['wifi', 'tv'],
    extraInfo: 'Snorkeling gear and canoe included. Breakfast delivered by canoe optional.',
    maxGuests: 2,
    price: 700,
  },
  {
    title: 'Craftsman Bungalow in East Nashville',
    address: 'Nashville, Tennessee, United States',
    photos: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    description: 'Beautifully restored 1920s Craftsman bungalow in East Nashville\'s music row. Original built-ins, a front porch with rocking chairs, and a record player with vinyl collection.',
    perks: ['wifi', 'parking', 'tv', 'pets'],
    extraInfo: 'Walking distance to honky-tonks and live music venues. Guitar available.',
    maxGuests: 4,
    price: 145,
  },
  {
    title: 'Riad with Pool in the Medina',
    address: 'Fez, Morocco',
    photos: [
      'https://images.unsplash.com/photo-1539437829697-1b4ed5aebd19?w=800',
      'https://images.unsplash.com/photo-1528255671579-01b9e182ed1d?w=800',
    ],
    description: 'Exquisite riad hidden in the ancient Fez Medina. Zellige tilework, a central courtyard with plunge pool, and a rooftop terrace with views over the old city.',
    perks: ['wifi', 'tv'],
    extraInfo: 'Breakfast and hammam session included. Medina guide available.',
    maxGuests: 4,
    price: 80,
  },
  {
    title: 'Secluded Beach House',
    address: 'Byron Bay, New South Wales, Australia',
    photos: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
    ],
    description: 'Laid-back beach house steps from Wategos Beach. Surfboards in the garage, an outdoor shower, and a wraparound deck with ocean views and BBQ.',
    perks: ['wifi', 'parking', 'tv', 'pets'],
    extraInfo: 'Surfboards and wetsuits provided. Farmers market every Thursday.',
    maxGuests: 6,
    price: 225,
  },
  {
    title: 'Boutique Apartment in Palermo Soho',
    address: 'Buenos Aires, Argentina',
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    description: 'Stylish apartment in the vibrant Palermo Soho neighborhood. Exposed brick, designer furnishings, and a balcony overlooking tree-lined streets full of boutiques and cafes.',
    perks: ['wifi', 'tv', 'entrance'],
    extraInfo: 'Tango lesson voucher included. Amazing steakhouses within walking distance.',
    maxGuests: 3,
    price: 70,
  },
  {
    title: 'Clifftop Villa in Uluwatu',
    address: 'Uluwatu, Bali, Indonesia',
    photos: [
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
    ],
    description: 'Dramatic clifftop villa perched above the Indian Ocean. Infinity pool seemingly merging with the sea, open-air living pavilion, and world-class surf breaks below.',
    perks: ['wifi', 'parking', 'tv'],
    extraInfo: 'Private chef and driver included. Kecak fire dance at the temple nightly.',
    maxGuests: 8,
    price: 420,
  },
  {
    title: 'Penthouse in the Gothic Quarter',
    address: 'Barcelona, Spain',
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    description: 'Top-floor apartment in Barcelona\'s Gothic Quarter with a private rooftop terrace. Views of the cathedral spires, Mediterranean light, and Gaudi just around the corner.',
    perks: ['wifi', 'tv', 'entrance'],
    extraInfo: 'No elevator (5th floor). Sangria kit in the fridge. Flamenco shows nearby.',
    maxGuests: 4,
    price: 185,
  },
  {
    title: 'Prairie Homestead with Horses',
    address: 'Montana, United States',
    photos: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
      'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800',
    ],
    description: 'Working ranch homestead on 500 acres of Montana prairie. Wake up to mountain views, ride horses, and enjoy home-cooked meals around a campfire under endless skies.',
    perks: ['wifi', 'parking', 'pets'],
    extraInfo: 'Horseback riding included. Fly fishing on the creek. Cell service is limited.',
    maxGuests: 6,
    price: 155,
  },
  {
    title: 'Hanok Stay in Bukchon',
    address: 'Seoul, South Korea',
    photos: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
    ],
    description: 'Traditional Korean hanok in the historic Bukchon village. Ondol heated floors, sliding paper doors, and a serene courtyard garden. Between two UNESCO palaces.',
    perks: ['wifi', 'tv'],
    extraInfo: 'Hanbok rental and tea ceremony available. Remove shoes indoors.',
    maxGuests: 3,
    price: 100,
  },
  {
    title: 'Jungle Pavilion with Pool',
    address: 'Tulum, Quintana Roo, Mexico',
    photos: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800',
    ],
    description: 'Open-air jungle pavilion with a cenote-inspired pool. Thatched palapa roof, outdoor rain shower, and a path through the jungle leading to a private beach club.',
    perks: ['wifi', 'parking', 'tv', 'pets'],
    extraInfo: 'Bikes provided for beach access. Cenote tours and Mayan ruin visits arranged.',
    maxGuests: 4,
    price: 245,
  },
  {
    title: 'Victorian Terrace in Notting Hill',
    address: 'London, England, United Kingdom',
    photos: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    description: 'Pastel-colored Victorian terrace house on a quintessential Notting Hill street. Period features, private garden, and the Portobello Road Market at your doorstep.',
    perks: ['wifi', 'tv', 'entrance'],
    extraInfo: 'Tube station 3-minute walk. Antique market every Saturday.',
    maxGuests: 5,
    price: 275,
  },
  {
    title: 'Cave Hotel Room in Cappadocia',
    address: 'Goreme, Cappadocia, Turkey',
    photos: [
      'https://images.unsplash.com/photo-1539437829697-1b4ed5aebd19?w=800',
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800',
    ],
    description: 'Carved into ancient volcanic rock, this cave suite features arched stone ceilings, a jacuzzi, and a terrace with views of fairy chimneys and hot air balloons at sunrise.',
    perks: ['wifi', 'tv'],
    extraInfo: 'Hot air balloon flights booked on request. Pottery workshop available.',
    maxGuests: 2,
    price: 165,
  },
  {
    title: 'Plantation House with Veranda',
    address: 'Charleston, South Carolina, United States',
    photos: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    description: 'Stately antebellum home with double-decker verandas, oak-lined drive, and lush gardens. Period antiques, four-poster beds, and sweet tea on the porch.',
    perks: ['wifi', 'parking', 'tv', 'pets'],
    extraInfo: 'Carriage ride tours bookable. Southern breakfast included on weekends.',
    maxGuests: 8,
    price: 260,
  },
  {
    title: 'Modern Cabin on a Fjord',
    address: 'Tromsø, Norway',
    photos: [
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800',
      'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800',
    ],
    description: 'Architect-designed cabin on the edge of a Norwegian fjord. Floor-to-ceiling glass, a wood-fired sauna, and a private dock for kayaking under the midnight sun.',
    perks: ['wifi', 'parking'],
    extraInfo: 'Kayaks and fishing gear provided. Northern lights visible September–March.',
    maxGuests: 4,
    price: 240,
  },
  {
    title: 'Courtyard Riad in Essaouira',
    address: 'Essaouira, Morocco',
    photos: [
      'https://images.unsplash.com/photo-1528255671579-01b9e182ed1d?w=800',
      'https://images.unsplash.com/photo-1539437829697-1b4ed5aebd19?w=800',
    ],
    description: 'Wind-swept coastal riad with a sun-drenched courtyard and rooftop with Atlantic Ocean views. Blue shutters, bougainvillea, and the scent of sea air and spices.',
    perks: ['wifi', 'tv'],
    extraInfo: 'Surfing and windsurfing lessons arranged. Fresh seafood market nearby.',
    maxGuests: 4,
    price: 70,
  },
  {
    title: 'Lakeside Cabin in Queenstown',
    address: 'Queenstown, New Zealand',
    photos: [
      'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800',
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800',
    ],
    description: 'Timber cabin on the shores of Lake Wakatipu with the Remarkables as a backdrop. Private hot tub, fire pit, and access to hiking, bungee jumping, and jet boat rides.',
    perks: ['wifi', 'parking', 'tv', 'pets'],
    extraInfo: 'Adventure activity discounts for guests. BBQ and outdoor dining area.',
    maxGuests: 5,
    price: 200,
  },
  {
    title: 'Rooftop Flat in the Medina',
    address: 'Chefchaouen, Morocco',
    photos: [
      'https://images.unsplash.com/photo-1539437829697-1b4ed5aebd19?w=800',
      'https://images.unsplash.com/photo-1528255671579-01b9e182ed1d?w=800',
    ],
    description: 'Blue-washed apartment in the famous blue city with a rooftop terrace overlooking the Rif Mountains. Hand-painted tiles, woven rugs, and mint tea on arrival.',
    perks: ['wifi'],
    extraInfo: 'Hike to the Spanish Mosque for sunset views. No cars in the medina.',
    maxGuests: 3,
    price: 45,
  },
];

router.post('/', async (req, res) => {
  try {
    // Clear existing seed data and re-seed
    await Place.deleteMany({});

    // Create a demo user
    let demoUser = await User.findOne({ email: 'demo@airbnb-clone.com' });
    if (!demoUser) {
      demoUser = await User.create({
        name: 'Demo Host',
        email: 'demo@airbnb-clone.com',
        password: 'demo123456',
      });
    }

    // Create all listings
    const places = await Place.insertMany(
      SAMPLE_LISTINGS.map((listing) => ({
        ...listing,
        owner: demoUser._id,
      }))
    );

    res.status(201).json({
      message: `Seeded ${places.length} listings successfully`,
      seeded: true,
      count: places.length,
    });
  } catch (error) {
    console.error('Seed error:', error);
    res.status(500).json({ message: 'Failed to seed database', error: error.message });
  }
});

module.exports = router;
